name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - ebs-deployment

env:
  AWS_REGION: ap-southeast-1
  EB_APPLICATION: nimble1
  EB_ENVIRONMENT: Nimble1-env
  DOCKER_BUILDKIT: 1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Frontend
        env:
          VITE_API_URL: http://${{ env.EB_APPLICATION }}.ap-southeast-1.elasticbeanstalk.com
        run: |
          cd frontend
          docker build --build-arg VITE_API_URL=$VITE_API_URL -t frontend-prod --target production .
          docker run --rm -v $(pwd)/dist:/app/dist frontend-prod npm run build

      - name: Generate production environment file
        run: |
          cd backend
          echo "APP_NAME=NimbleScraper" > .env
          echo "APP_ENV=production" >> .env
          echo "APP_KEY=${{ secrets.APP_KEY }}" >> .env
          echo "APP_DEBUG=false" >> .env
          echo "APP_URL=http://${{ env.EB_APPLICATION }}.ap-southeast-1.elasticbeanstalk.com" >> .env
          echo "DB_CONNECTION=pgsql" >> .env
          echo "DB_HOST=google-scraper-db.cappcslmdagl.ap-southeast-1.rds.amazonaws.com" >> .env
          echo "DB_PORT=5432" >> .env
          echo "DB_DATABASE=google-scraper-db" >> .env
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}" >> .env
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env

      - name: Create Dockerrun.aws.json
        run: |
          echo '{
            "AWSEBDockerrunVersion": "1",
            "Image": {
              "Name": "php:8.2-fpm",
              "Update": "true"
            },
            "Ports": [
              {
                "ContainerPort": "80"
              }
            ]
          }' > Dockerrun.aws.json

      - name: Create deployment package
        run: |
          # Copy frontend dist to backend public
          cp -r frontend/dist/* backend/public/
          
          # Create deployment package
          zip -r deploy-${{ github.sha }}.zip backend/* Dockerrun.aws.json

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.EB_APPLICATION }}
          environment_name: ${{ env.EB_ENVIRONMENT }}
          region: ${{ env.AWS_REGION }}
          deployment_package: deploy-${{ github.sha }}.zip
          version_label: ${{ github.sha }}
          wait_for_deployment: true
          deployment_description: "Deploy from GitHub Actions"
